sudo: required

language: node_js

node_js:
  - 8.11.3

services:
  - docker

before_install:
  - docker build -t my-postgres -f docker/db/Dockerfile .
  - docker run --name test-db --env-file .env -p 5437:5432 -d my-postgres
  - docker ps -a

env:
  - DATABASE_PORT=5437

jobs:
  include:
    - node_js: node
      script: jest --coverage --runInBand --coverageReporters=text-lcov | coveralls

deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_AUTH_TOKEN
  on:
    repo: SuNR0N/crud-server-demo-app