version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: .env